# Generated by Django 4.1.3 on 2022-11-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors',
            name='email',
            field=models.EmailField(default='@mail.ru', max_length=254),
        ),
    ]
