# Generated by Django 4.1.3 on 2022-11-26 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_directors_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('year', models.IntegerField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, default=1000000, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('DOL', 'Dollar'), ('RUB', 'Rubles')], default='RUB', max_length=3)),
                ('slug', models.SlugField(default='')),
                ('actors', models.ManyToManyField(to='movie_app.actors')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.directors')),
            ],
        ),
    ]
